# Generated by Django 5.2.5 on 2025-09-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_birth_chart_calculated',
            field=models.BooleanField(default=False, verbose_name='Harita Hesaplandı mı?'),
        ),
    ]
