# Generated by Django 5.2.5 on 2025-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(choices=[('Aries', 'Koç'), ('Taurus', 'Boğa'), ('Gemini', 'İkizler'), ('Cancer', 'Yengeç'), ('Leo', 'Aslan'), ('Virgo', 'Başak'), ('Libra', 'Terazi'), ('Scorpio', 'Akrep'), ('Sagittarius', 'Yay'), ('Capricorn', 'Oğlak'), ('Aquarius', 'Kova'), ('Pisces', 'Balık')], db_index=True, max_length=20, verbose_name='Burç')),
                ('comment_type', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık')], db_index=True, max_length=10, verbose_name='Yorum Tipi')),
                ('date', models.DateField(db_index=True, verbose_name='Tarih')),
                ('prediction_data', models.JSONField(verbose_name='Tahmin Verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Burç Yorumu',
                'verbose_name_plural': 'Burç Yorumları',
                'ordering': ['-date', 'sign'],
                'unique_together': {('sign', 'comment_type', 'date')},
            },
        ),
    ]
