# Generated by Django 5.2.5 on 2025-08-16 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Engellenen')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Engelleyen')),
            ],
            options={
                'verbose_name': 'Engelleme',
                'verbose_name_plural': 'Engellemeler',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Skor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uyumluluk',
                'verbose_name_plural': 'Uyumluluklar',
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='DailyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('matched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_match_for', to=settings.AUTH_USER_MODEL, verbose_name='Eşleştiği Kullanıcı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_match', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Günün Eşleşmesi',
                'verbose_name_plural': 'Günün Eşleşmeleri',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to=settings.AUTH_USER_MODEL, verbose_name='Beğenilen')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_likes', to=settings.AUTH_USER_MODEL, verbose_name='Beğenen')),
            ],
            options={
                'verbose_name': 'Beğeni',
                'verbose_name_plural': 'Beğeniler',
                'unique_together': {('liker', 'liked')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eşleşme',
                'verbose_name_plural': 'Eşleşmeler',
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='SuperLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_super_likes', to=settings.AUTH_USER_MODEL, verbose_name='Süper Beğenilen')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_super_likes', to=settings.AUTH_USER_MODEL, verbose_name='Süper Beğenen')),
            ],
            options={
                'verbose_name': 'Süper Beğeni',
                'verbose_name_plural': 'Süper Beğeniler',
                'unique_together': {('liker', 'liked')},
            },
        ),
    ]
