# Generated by Django 5.2.5 on 2025-09-17 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_passes', to=settings.AUTH_USER_MODEL, verbose_name='Geçilen')),
                ('passer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_passes', to=settings.AUTH_USER_MODEL, verbose_name='Geçen')),
            ],
            options={
                'verbose_name': 'Geçme',
                'verbose_name_plural': 'Geçmeler',
                'unique_together': {('passer', 'passed')},
            },
        ),
    ]
