# Generated by Django 5.2.5 on 2025-09-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibility',
            name='breakdown',
            field=models.JSONField(blank=True, null=True, verbose_name='Uyumluluk Dökümü'),
        ),
    ]
