# Generated by Django 5.2.5 on 2025-08-16 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket Adı')),
                ('product_id_apple', models.CharField(help_text="App Store Connect'teki Ürün ID'si", max_length=255, unique=True, verbose_name='Apple Product ID')),
                ('product_id_google', models.CharField(help_text="Google Play Console'daki Ürün ID'si", max_length=255, unique=True, verbose_name='Google Product ID')),
                ('duration_days', models.PositiveIntegerField(help_text='Bu paketin kaç gün geçerli olduğu', verbose_name='Süre (Gün)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store', models.CharField(choices=[('apple', 'Apple App Store'), ('google', 'Google Play Store')], max_length=10, verbose_name='Mağaza')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='İşlem ID')),
                ('purchase_token', models.TextField(verbose_name="Satın Alma Token'ı")),
                ('purchase_date', models.DateTimeField(verbose_name='Satın Alma Tarihi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulandı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan', verbose_name='Satın Alınan Paket')),
            ],
            options={
                'verbose_name': 'Satın Alma İşlemi',
                'verbose_name_plural': 'Satın Alma İşlemleri',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(db_index=True, verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif mi?')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan', verbose_name='Abonelik Paketi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Aboneliği',
                'verbose_name_plural': 'Kullanıcı Abonelikleri',
            },
        ),
    ]
